name: Unit Test

on:
  push:
    branches: [ "**" ]
    paths:
      - 'ci/ut/**/*.go'
      - 'ci/ut/go.mod'
      - 'ci/ut/go.sum'
  pull_request:
    branches: [ "**" ]
    paths:
      - 'ci/ut/**/*.go'
      - 'ci/ut/go.mod'
      - 'ci/ut/go.sum'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ci/ut

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache-dependency-path: ci/ut/go.mod

    - name: Build only the main application
      run: |
        cd cmd/fizzbuzz
        go build -v .

    - name: Run unit tests
      run: |
        cd pkg/fizzbuzz
        go test -v .
